version: '3.1'

services:

  db:
    image: postgre:sck-11.5
    container_name: postgre
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  hello:
    image: hello:1.0
    ports: 
      - 9090:9090

      
